development:
  adapter: postgresql
  database: auction_calendar_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: auction_calendar_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: auction_calendar_production
  pool: 5
  timeout: 5000
