development:
  adapter: postgresql
  database: action_calander_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: action_calander_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: action_calander_production
  pool: 5
  timeout: 5000
